name: flutter_thirukural
description: >
  A Flutter package to seamlessly integrate the holy tamil literature "Thirukural"
  into your apps, with support for full access to all 1330 kurals, categorized views 
  by sections, chapters (both Tamil and English), search by number or range, and 
  kural of the day. All widgets are self-contained and ready to use!

version: 1.2.0

homepage: https://github.com/SanjayPrasathG/flutter_thirukural
repository: https://github.com/SanjayPrasathG/flutter_thirukural
issue_tracker: https://github.com/SanjayPrasathG/flutter_thirukural/issues

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

topics:
  - flutter
  - thirukural
  - tamil
  - kural

dependencies:
  flutter:
    sdk: flutter
  responsive_framework: ^1.5.1
  hooks_riverpod: ^2.6.1
  logger: ^2.5.0
  dio: ^5.8.0+1
  google_fonts: ^6.2.1
  flutter_hooks: ^0.21.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

